language: node_js
node_js:
- node
sudo: required
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libgemplugin-ruby wine
- sudo gem install sass
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
- winetricks -q dotnet20
script:
- npm start
cache:
  directories:
  - cache
env:
  global:
  - secure: mhoxSislcDbRMgghIDIXmgWrbi8WrsPaFTuyO7J/RXef8zLM/EZn3F06w8toyyMW4eAfvt94irvih/me5lFuHxQl4aRD6hj/Ot4gIo6oiP4JAYLXnkZS1TwJxfMUr2FUcYpl0DLl3+TFCEIa6X3+sgD3qOjwOvDcuaCMnjkNLqEwzhYLJUq6q1f7OEN7m3FEg2VKnh3B9P2Iujh9OJ6nkC0g+r0tP9dcMUnz45rb6BHSw2JNs7UXyPYNfP1dUXnUfZCMIy6o+JsQceWpD/lFwE4iqrTZTOzgoejlN1erfY+CBglYAunq7GtOYQSIozZlxVACEyzHYKBcVHWt/OXWQwpHca2cMng24ufebKpeboYHFdnP5KlcOBNeqQS4dEnTQiZkwJEpDtdH5dDHiY3lvz/HuLhaQWj2AQVDDz95cab6zyE2Yxaj4ERadmMV/b1HxKtDcsSnl4UQsQhcrOXvFomJXyPRNAt+QhDVts020AnvYZcFWNHWMbkI2dZ4eLEkrbamWzkE2WCgB0hgK/8UF3q6f+zKfwA/0JaPA89YQg20oi9VGfYlMgAa4HzjerKx+odOhbWr2GB5j5cw2SQcG98XD3JwkFlEbkzc2/MGwkuXNp5GOLR+YjbB9JdBSFXN1dN4ohvIJPF6v0TP4OJd9BwrdL6xtyyzcEZOcHy0ltc=
